<a href="https://colab.research.google.com/github/NitinKarthik01/AIML_MSIS/blob/main/numpy_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity 1

import numpy as np
a = np.array([10,20,30,40])
b = np.arange(1,11)
c= np.linspace(1,10,6)
print(a)
print(b)
print(c)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.   2.8  4.6  6.4  8.2 10. ]


In [ ]:
#Activity 2

A = np.array([[10,20], [30,40]])
print(A)
B = np.array([[50,60], [70,80]])
print(B)
print(" ")
print("A+B is ", A+B)
print(" ")
print("A-B is ", A-B)
print(" ")
print("A*B is ", A*B)
print(" ")
print("A/B is ", A/B)

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]
 
A+B is  [[ 60  80]
 [100 120]]
 
A-B is  [[-40 -40]
 [-40 -40]]
 
A*B is  [[ 500 1200]
 [2100 3200]]
 
A/B is  [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#Activity 3

marks = np.array([10,20,30,40,50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

150
30.0
50
10
14.142135623730951


take weather dsat of last july month of udupi and find the hottest and coldest day in udupi
calculate the avg of tempertature of overall month
find which all dates  of temertature above 30 degrees

In [ ]:
#Activity 4

Temperature = np.array([
    27.0, 27.5, 28.0, 27.2, 26.8, 27.4, 27.9, 28.1, 27.5, 27.0,
    26.9, 27.3, 27.8, 28.2, 27.7, 27.1, 26.8, 27.2, 27.6, 28.0,
    27.4, 27.0, 26.7, 27.1, 27.5, 27.9, 28.3, 27.8, 27.2, 26.9, 27.3
])

indices = np.where(Temperature == np.max(Temperature))[0]
print(" the hottest day of the month is",indices+1,"July")
print(" ")

indices2 = np.where(Temperature == np.min(Temperature))[0]
print("The Coldest day of month is ", indices2 +1,"July")
print(" ")

print("The Average Temperature of month is ", np.mean(Temperature))
print(" ")


indices3 = np.where(Temperature>30)[0]
print(indices3)


 the hottest day of the month is [27] July
 
The Coldest day of month is  [23] July
 
The Average Temperature of month is  27.422580645161286
 
[]
